# Generated by Django 4.0.4 on 2022-06-20 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('cp', models.IntegerField(verbose_name='Codigo Postal')),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('usuario', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='ImagenCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media_clientes', verbose_name='Imagen Documento')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ClientesApp.cliente')),
            ],
            options={
                'verbose_name': 'Imagen Cliente',
                'verbose_name_plural': 'Imagenes Clientes',
                'ordering': ['cliente'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.TextField(max_length=500, verbose_name='Consulta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='ClientesApp.cliente')),
            ],
        ),
    ]
