# Generated by Django 4.0.4 on 2022-06-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0002_alter_cliente_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, verbose_name='Pregunta')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
            ],
        ),
    ]
